name: Test Suite

# Controls when the action will run.
on:
  # Triggers the workflow on push for the master branch.
  push:
    branches: [ master ]
  # Triggers the workflow on pull request for any branch.
  pull_request:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
        django-version: [ "4.2" ]
    steps:
      # Checks-out the  repository.
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            dev_requirements.txt

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -q Django==${{ matrix.django-version }}

      - name: Install Cache Helper Package
        run: pip install -e .

      - name: Run tests
        run: |
          coverage run --source='../cache_helper' --data-file='../.coverage.${{ matrix.python-version }}.${{ matrix.django-version }}' manage.py test
        working-directory: ./test_project

      - name: Create LCOV file
        run: |
          coverage lcov --data-file='.coverage.${{ matrix.python-version }}.${{ matrix.django-version }}'

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.python-version }}-${{ matrix.django-version }}
          path-to-lcov: coverage.lcov
          parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
